"""
GBO -- Guest-mode Pitcher Profile deep dive (Sept 2026).

Renders the "sample Pitcher Profile" section of the Continue-as-Guest
page: one fictional pitcher (see demo_data.py -- nobody real, no real
data), scored with the exact same analytics functions the live
Pitcher Profile page uses, with dual coach/player explanations,
methodology call-outs, and citations layered around the numbers.

The origin-story paragraph and the Stuff+ methodology story below are
written in Ryker's own first-person voice -- the technical claims in
both (the regression-overfit example, the fixed-weight fix) are pulled
straight from analytics/pitch_grading.py's own comments, so they're
accurate as written. Worth a re-read after any real change to that
methodology, since this page doesn't update itself.

This is intentionally scoped to ONE page (Pitcher Profile) for this
first pass. As GBO adds features, this file -- and the rest of
_guest_ui() in app.py -- needs the same kind of update: a new
deep-dive section here, or a refreshed line in the existing site-map
content, whenever a module changes enough that this page no longer
describes the real one accurately.
"""

from shiny import ui

import demo_data
import ui_helpers


def _grade_card(pitch_type_label, grades):
    stuff = grades.get("stuff_plus")
    location = grades.get("location_plus")
    pitching = grades.get("pitching_plus")
    return ui.div(
        ui.p(ui.strong(pitch_type_label), style="margin-bottom:6px;"),
        ui.div(
            ui_helpers.kpi_tile("Stuff+", stuff if stuff is not None else "—"),
            ui_helpers.kpi_tile("Location+", location if location is not None else "—"),
            ui_helpers.kpi_tile("Pitching+", pitching if pitching is not None else "—"),
            class_="gbo-kpi-row",
        ),
        ui.p(
            f"{grades.get('n_bullpen', 0)} bullpen/Rapsodo readings, {grades.get('n_located', 0)} located game pitches "
            "behind this pitch type's numbers.",
            class_="text-muted small", style="margin-top:4px;",
        ),
        class_="gbo-profile-card", style="padding:14px; margin-bottom:12px;",
    )


def _role_callout(coach_text, player_text):
    return ui.div(
        ui.div(
            ui.p(ui.strong("A coach uses this to: "), coach_text, style="margin-bottom:4px;"),
            ui.p(ui.strong("A player uses this to: "), player_text, style="margin-bottom:0;"),
            class_="text-muted small",
        ),
        style="border-left:3px solid var(--gbo-accent-ink, #BF1E2D); padding-left:12px; margin:10px 0 16px;",
    )


def _citation(text):
    return ui.p(ui.em(text), class_="text-muted small", style="margin-top:2px;")


def build_pitcher_profile_deep_dive():
    report = demo_data.demo_pitcher_report()
    player = report["player"]
    full_name = f"{player.first_name} {player.last_name}"

    grade_cards = [
        _grade_card(label, grades)
        for label, grades in sorted(report["grades"].items(), key=lambda kv: -kv[1]["n_bullpen"])
    ]

    command = report["command"]
    bias = report["miss_bias"]

    return ui.div(
        ui.h4("Sample Pitcher Profile", class_="gbo-section-title"),
        ui.p(
            ui.strong(full_name), " is not a real player. ", ui.strong("Every number on this page is synthetic"),
            " -- generated by demo_data.py, then scored by the exact same GBO analytics functions (Stuff+, "
            "Location+, Pitching+, Command+, Estimated Arm Angle, Estimated VAA) that run on real Rapsodo and "
            "game-charting data for the real Pittsburg State roster. Nothing here is connected to the real "
            "database, and no real player's data was used to build it.",
        ),
        ui.p(
            "I started building Gorilla Baseball Operations as my Master's research project at Pittsburg "
            "State, and it grew well past that. I'm also a pitcher on the team, so I built this the way I "
            "wish a tool like it had existed for me -- one place for physical testing, development plans, "
            "training logs, Rapsodo pitch data, and in-game performance, instead of that living across "
            "spreadsheets, paper testing sheets, and a handful of disconnected tools. I designed and built "
            "the whole thing myself: the database schema, every page, and the analytics underneath it. "
            "Pitcher Profile is the one page I'd show first if I only got to show one.",
        ),
        ui.p(
            "It's GBO's flagship analytics view -- a single, filterable deep dive into one pitcher's stuff, "
            "command, and results, built so a coach and that pitcher can look at the exact same page and both "
            "get something useful out of it. Unlike a coach's roster-wide dashboard or a player's own personal "
            "schedule (both look different depending on who's logged in -- see the role-based dashboards "
            "further down this page), Pitcher Profile renders identically for a coach and for the pitcher "
            "himself, by design: there's no simplified or hidden version of a player's own numbers. The "
            "\"how a coach uses this\" and \"how a player uses this\" notes below each section are about how "
            "the two read the same page differently, not two different pages.",
        ),

        ui.hr(),
        ui.h5("Physical Profile — what Rapsodo actually measures"),
        ui.p(
            "Every pitch type this pitcher throws, averaged: velocity, spin rate, movement (IVB/HB), release "
            "point, Estimated Arm Angle, and Estimated VAA. This is the same table structure the real Pitcher "
            "Profile page shows on its Metrics tab."
        ),
        ui_helpers.render_dict_table(report["physical_rows"]),
        _role_callout(
            "spot a mechanical change before it shows up in results — a release height that's drifted an inch, "
            "an arm angle that's shifted a few degrees between bullpens — and start a conversation with the "
            "pitcher about it early, not after it's cost him a month of results.",
            "see their own stuff in the same objective terms a coach or a pro scout would use, instead of relying "
            "purely on feel or what a radar gun says about velocity alone.",
        ),
        _citation(
            "Estimated Arm Angle and Estimated VAA are GBO's own geometric estimates from release point and "
            "extension, not a direct Rapsodo measurement -- built because our indoor bullpen setup doesn't "
            "always report a real plate-crossing angle. The idea that approach angle (not just velocity or spin "
            "rate) drives how hittable a fastball is comes from Alex Chamberlain's Pitch Leaderboard and "
            "Pitcher List's public writing on vertical approach angle."
        ),

        ui.hr(),
        ui.h5("Stuff+ / Location+ / Pitching+ — pitch quality, on a 100-point scale"),
        ui.p(
            "100 = this pitcher's own team's average on that pitch type; each 10 points is roughly one standard "
            "deviation better or worse than that average. There's no real MLB benchmark behind these numbers -- "
            "GBO doesn't have access to league-wide pitch-tracking data, so every score here answers \"better or "
            "worse than this roster's own average,\" never \"better or worse than a real MLB Stuff+.\""
        ),
        *grade_cards,
        _role_callout(
            "see, pitch type by pitch type, whether a guy's results are being driven by genuinely good stuff "
            "(Stuff+), by where he's throwing it (Location+), or both (Pitching+) -- which is a very different "
            "development conversation for each case.",
            "understand which part of their own game the numbers say to actually work on -- a pitcher with a "
            "strong Stuff+ but a weak Location+ has a very different bullpen focus than the reverse.",
        ),
        ui.accordion(
            ui.accordion_panel(
                "How Stuff+'s weights were actually picked (not a regression)",
                ui.p(
                    "Stuff+ started as a fixed, equal-weighted formula that never learned anything from real "
                    "outcomes -- it scored a bullpen pitch and a real-game pitch identically, with no connection "
                    "to what actually happened when the ball was put in play. My first fix was the textbook "
                    "approach: fit a regression per pitch type, weighting each physical trait (velocity, "
                    "movement, spin efficiency, and so on) by how much it actually predicted run value in our "
                    "own games."
                ),
                ui.p(
                    "That fell apart in practice. Fitting roughly ten parameters per pitch type off a few dozen "
                    "to a couple hundred real-game pitches is exactly the small-sample regime where a regression "
                    "starts memorizing noise instead of learning anything real. The concrete example that made me "
                    "pull it: one pitcher's 2-Seam Fastball scored a Stuff+ of 108 against a teammate's ~88-93 -- "
                    "despite that first pitcher throwing 3-4 mph slower with less horizontal break. The fitted "
                    "model had decided release side and gyro degree explained almost everything, and velocity's "
                    "own weight came out tiny, and backwards-signed. That's not a real signal; that's a "
                    "regression artifact of a training pool that's still too small."
                ),
                ui.p(
                    "So Stuff+'s weights are now fixed, hand-set once per pitch type, informed by outside public "
                    "research on pitch quality (aStuff+, Driveline, and Rockland's published work) and general "
                    "pitch-design principles for what actually makes each pitch type good -- not fit from our "
                    "own limited sample. What IS still real, GBO-derived data is the baseline each pitch is "
                    "compared against: for every feature, I compute this team's own mean and standard deviation "
                    "and standardize against that, so the composite still means \"how far from this roster's own "
                    "average,\" it's just combined with a fixed weight instead of a fitted one. As the program "
                    "collects more seasons of real outcome data, revisiting these weights with an actual "
                    "regression is the obvious next step -- this is a considered, temporary trade-off for a "
                    "one-program's-worth-of-data problem, not a belief that fixed weights are the final answer."
                ),
                _citation(
                    "Structure (what Stuff+/Location+/Pitching+ each measure, and why Location+ deliberately "
                    "leaves out stringer-judged intent) is based on FanGraphs' Stuff+, Location, and Pitching+ "
                    "primer (library.fangraphs.com/pitching/stuff-location-and-pitching-primer). The scoring "
                    "METHOD -- a team-relative z-score composite instead of FanGraphs' own league-trained "
                    "decision tree -- is GBO's own adaptation, made necessary by not having anywhere near "
                    "FanGraphs' data volume."
                ),
            ),
            open=False,
        ),

        ui.hr(),
        ui.h5("Command+ — how well he executes, adjusted for how hard the pitch is to spot up"),
        ui.p(
            f"Average miss from target: {command.get('avg_miss_distance')}\" (median {command.get('median_miss_distance')}\"). "
            f"Execution rate: {command.get('execution_pct')}% of located pitches. "
            f"Overall miss tendency: {bias.get('horizontal_bias_in')}\" {bias.get('horizontal_bias_label')}, "
            f"{bias.get('vertical_bias_in')}\" {bias.get('vertical_bias_label')}."
        ),
        _role_callout(
            "run a real bullpen-command evaluation instead of an eye test -- and, because Command+ is graded "
            "pitch-type by pitch-type against this team's own baseline for that type, compare a fastball's "
            "command fairly against a much-harder-to-locate slider instead of penalizing whoever throws more "
            "breaking stuff.",
            "get an honest answer to \"am I actually missing my spots, and which direction do I tend to miss\" -- "
            "the miss-bias number below specifically answers whether misses trend arm-side/glove-side or "
            "high/low, which is usually the more actionable half of a command problem.",
        ),
        _citation(
            "The pitch-type-fair version of Command+ (grading each pitch type against its own team baseline "
            "rather than one pooled average) was prompted by FanGraphs' \"Kirby Index\" piece on why pooling "
            "command across pitch types of very different difficulty distorts the picture."
        ),

        ui.hr(),
        ui.div(
            ui.h5("Research: does conditioning type actually change how a fastball plays under fatigue?", class_="gbo-section-title"),
            ui.p(
                ui.strong("Coming soon."), " I'm running two related research threads alongside GBO itself: a "
                "correlation study checking whether the Bucket System's physical-testing categories (strength, "
                "power, speed) actually predict fastball velocity and spin rate, and a Master's thesis testing "
                "whether conditioning type (aerobic/endurance vs. sprint/interval vs. a hybrid) changes fatigue "
                "and pitching performance over the course of a game or a season. Once those correlations are run "
                "against real data, this section will walk through the testing battery, the study design, and "
                "the actual findings -- the same way the sections above walk through Stuff+ and Command+."
            ),
            class_="gbo-profile-card", style="padding:16px; border-style:dashed;",
        ),
        ui.hr(),
        ui.p(
            "This deep dive covers one page. Bullpen Tracking, Game Tracking, Assessments, and the rest of GBO "
            "are still described only at a high level further down -- expanding those with the same kind of "
            "walkthrough is the natural next update to this page.",
            class_="text-muted small",
        ),
    )
